version: '2'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 33060:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: db
  mongo:
    image: mongo:4.0-xenial
    ports:
      - 27016:27017
